<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Report - {{ $companyName }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            color: #333;
            line-height: 1.4;
        }
        .header {
            background: #1e40af;
            color: white;
            padding: 20px;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 20px;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 11px;
            opacity: 0.9;
        }
        .info-box {
            background: #f3f4f6;
            padding: 12px;
            margin-bottom: 15px;
            border-left: 4px solid #3b82f6;
        }
        .info-box p {
            margin: 3px 0;
            font-size: 9px;
        }
        .info-box strong {
            color: #1e40af;
        }
        .section-title {
            font-size: 14px;
            font-weight: bold;
            color: #1f2937;
            margin: 20px 0 10px 0;
            padding-bottom: 5px;
            border-bottom: 2px solid #e5e7eb;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-box {
            display: table-cell;
            width: 25%;
            padding: 12px;
            text-align: center;
            border: 1px solid #e5e7eb;
        }
        .stat-box .label {
            font-size: 9px;
            color: #6b7280;
            text-transform: uppercase;
        }
        .stat-box .value {
            font-size: 24px;
            font-weight: bold;
            color: #1f2937;
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th {
            background: #f9fafb;
            padding: 8px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
            color: #374151;
            border-bottom: 2px solid #e5e7eb;
        }
        td {
            padding: 6px 8px;
            font-size: 9px;
            border-bottom: 1px solid #f3f4f6;
        }
        .progress-bar {
            background: #e5e7eb;
            height: 8px;
            border-radius: 4px;
            overflow: hidden;
            display: inline-block;
            width: 100px;
            vertical-align: middle;
        }
        .progress-fill {
            background: #3b82f6;
            height: 100%;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            font-size: 8px;
            font-weight: bold;
            border-radius: 3px;
        }
        .badge-blue { background: #dbeafe; color: #1e40af; }
        .badge-green { background: #d1fae5; color: #065f46; }
        .badge-yellow { background: #fef3c7; color: #92400e; }
        .badge-red { background: #fee2e2; color: #991b1b; }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #6b7280;
            padding: 10px;
            border-top: 1px solid #e5e7eb;
        }
        .metric-row {
            margin-bottom: 10px;
        }
        .metric-label {
            font-size: 9px;
            color: #6b7280;
            margin-bottom: 3px;
        }
        .metric-value {
            font-size: 18px;
            font-weight: bold;
            color: #1f2937;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>{{ $companyName }}</h1>
        <p>Ticket Reports & Analytics</p>
    </div>

    <!-- Report Info -->
    <div class="info-box">
        <p><strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}</p>
        <p><strong>Generated:</strong> {{ now()->format('F d, Y H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ $user->name }} ({{ ucfirst($userRole) }})</p>
        @if($userRole === 'customer')
        <p><strong>Scope:</strong> Personal tickets only</p>
        @elseif($userRole === 'agent')
        <p><strong>Scope:</strong> Assigned tickets only</p>
        @else
        <p><strong>Scope:</strong> All system tickets</p>
        @endif
    </div>

    <!-- Summary Statistics -->
    <div class="section-title">Summary Statistics</div>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="label">Total Tickets</div>
            <div class="value">{{ $data['totalTickets'] }}</div>
        </div>
        <div class="stat-box">
            <div class="label">Closed</div>
            <div class="value" style="color: #059669;">{{ $data['closedTickets'] }}</div>
        </div>
        <div class="stat-box">
            <div class="label">Open</div>
            <div class="value" style="color: #f59e0b;">{{ $data['openTickets'] }}</div>
        </div>
        <div class="stat-box">
            <div class="label">In Progress</div>
            <div class="value" style="color: #8b5cf6;">{{ $data['inProgressTickets'] }}</div>
        </div>
    </div>

    <!-- Performance Metrics -->
    <div class="section-title">Performance Metrics</div>
    <table style="margin-bottom: 20px;">
        <tr>
            <td style="width: 50%; border-right: 1px solid #e5e7eb;">
                <div class="metric-row">
                    <div class="metric-label">Average Response Time</div>
                    <div class="metric-value" style="color: #3b82f6;">{{ $data['avgResponseTime'] }}h</div>
                    <div style="font-size: 8px; color: #6b7280;">Time to first response</div>
                </div>
            </td>
            <td style="width: 50%; padding-left: 20px;">
                <div class="metric-row">
                    <div class="metric-label">Average Resolution Time</div>
                    <div class="metric-value" style="color: #059669;">{{ $data['avgResolutionTime'] }}h</div>
                    <div style="font-size: 8px; color: #6b7280;">Time to close ticket</div>
                </div>
            </td>
        </tr>
    </table>

    <!-- Tickets by Priority -->
    <div class="section-title">Tickets by Priority</div>
    <table>
        <thead>
            <tr>
                <th>Priority</th>
                <th>Count</th>
                <th style="width: 30%;">Distribution</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data['ticketsByPriority'] as $priority => $count)
            <tr>
                <td>{{ $priority }}</td>
                <td><strong>{{ $count }}</strong></td>
                <td>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: {{ $data['totalTickets'] > 0 ? ($count / $data['totalTickets'] * 100) : 0 }}%;"></div>
                    </div>
                    {{ $data['totalTickets'] > 0 ? round(($count / $data['totalTickets'] * 100), 1) : 0 }}%
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="3" style="text-align: center; color: #6b7280;">No data available</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Tickets by Category -->
    <div class="section-title">Tickets by Category</div>
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th>Count</th>
                <th style="width: 30%;">Distribution</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data['ticketsByCategory'] as $category => $count)
            <tr>
                <td>{{ $category }}</td>
                <td><strong>{{ $count }}</strong></td>
                <td>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: {{ $data['totalTickets'] > 0 ? ($count / $data['totalTickets'] * 100) : 0 }}%; background: #059669;"></div>
                    </div>
                    {{ $data['totalTickets'] > 0 ? round(($count / $data['totalTickets'] * 100), 1) : 0 }}%
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="3" style="text-align: center; color: #6b7280;">No data available</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Top Agents (if applicable) -->
    @if(in_array($userRole, ['administrator', 'agent']) && !$data['topAgents']->isEmpty())
    <div class="section-title">Top Performing Agents</div>
    <table>
        <thead>
            <tr>
                <th>Agent Name</th>
                <th>Tickets Handled</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['topAgents'] as $agent)
            <tr>
                <td>{{ $agent->name }}</td>
                <td><strong>{{ $agent->tickets_count }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Recent Tickets -->
    <div class="section-title">Recent Tickets (Last 10)</div>
    <table>
        <thead>
            <tr>
                <th style="width: 8%;">ID</th>
                <th style="width: 32%;">Subject</th>
                <th style="width: 15%;">Category</th>
                <th style="width: 15%;">Priority</th>
                <th style="width: 15%;">Status</th>
                <th style="width: 15%;">Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data['tickets'] as $ticket)
            <tr>
                <td>#{{ $ticket->id }}</td>
                <td>{{ \Str::limit($ticket->subject, 35) }}</td>
                <td>{{ $ticket->category->name ?? '-' }}</td>
                <td>{{ $ticket->priority->name ?? '-' }}</td>
                <td>{{ $ticket->status->name ?? '-' }}</td>
                <td>{{ $ticket->created_at->format('M d, Y') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center; color: #6b7280; padding: 20px;">No tickets found for this period</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>© {{ now()->year }} {{ $companyName }}. All rights reserved.</p>
        <p>This is an automatically generated report. Page 1 of 1</p>
    </div>
</body>
</html>
