@props([
    'id' => 'delete-modal',
    'title' => 'Delete Confirmation',
    'message' => 'Are you sure you want to delete this item? This action cannot be undone.',
    'confirmText' => 'DELETE',
    'cancelText' => 'CANCEL'
])

<div id="{{ $id }}" class="delete-modal" style="position: fixed; inset: 0; z-index: 100000; display: none; align-items: center; justify-content: center;">
    <!-- Backdrop -->
    <div class="delete-modal-backdrop" style="position: absolute; inset: 0; background-color: rgba(0, 0, 0, 0.5);" onclick="closeDeleteModal('{{ $id }}')"></div>
    
    <!-- Modal Content -->
    <div class="delete-modal-content" style="position: relative; background: white; border-radius: 6px; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25); max-width: 400px; width: 90%; margin: 1rem;">
        <!-- Header -->
        <div style="padding: 1rem 1.25rem; border-bottom: 1px solid #e5e7eb; display: flex; align-items: center; justify-content: space-between;">
            <div style="display: flex; align-items: center; gap: 0.5rem;">
                <span class="material-symbols-outlined" style="font-size: 20px; color: #dc2626;">warning</span>
                <h3 style="font-family: Poppins, sans-serif; font-size: 14px; font-weight: 600; color: #111827; margin: 0;">{{ $title }}</h3>
            </div>
            <button type="button" onclick="closeDeleteModal('{{ $id }}')" style="padding: 0.25rem; color: #6b7280; cursor: pointer; border: none; background: none;">
                <span class="material-symbols-outlined" style="font-size: 18px;">close</span>
            </button>
        </div>
        
        <!-- Body -->
        <div style="padding: 1.25rem;">
            <p style="font-family: Poppins, sans-serif; font-size: 12px; color: #4b5563; margin: 0 0 1rem 0; line-height: 1.5;">{{ $message }}</p>
            
            <!-- Verification Code Section -->
            <div style="background-color: #fef2f2; border: 1px solid #fecaca; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
                <p style="font-family: Poppins, sans-serif; font-size: 11px; color: #991b1b; margin: 0 0 0.5rem 0;">
                    To confirm deletion, please enter this code:
                </p>
                <div id="{{ $id }}-verification-code" style="font-family: 'Courier New', monospace; font-size: 24px; font-weight: bold; color: #dc2626; letter-spacing: 4px; text-align: center; padding: 0.5rem; background: white; border-radius: 4px; border: 1px dashed #fca5a5;">
                    <!-- Code will be generated by JS -->
                </div>
            </div>
            
            <!-- Input Field -->
            <div>
                <label style="font-family: Poppins, sans-serif; font-size: 11px; color: #374151; display: block; margin-bottom: 0.25rem;">
                    Enter verification code
                </label>
                <input type="text" 
                       id="{{ $id }}-code-input" 
                       maxlength="6" 
                       placeholder="Enter 6-character code"
                       autocomplete="off"
                       style="width: 100%; padding: 0.5rem 0.75rem; font-family: 'Courier New', monospace; font-size: 16px; letter-spacing: 4px; text-align: center; text-transform: uppercase; border: 1px solid #d1d5db; border-radius: 4px; outline: none; box-sizing: border-box;"
                       oninput="this.value = this.value.toUpperCase(); validateDeleteCode('{{ $id }}')">
                <p id="{{ $id }}-error-msg" style="font-family: Poppins, sans-serif; font-size: 10px; color: #dc2626; margin: 0.25rem 0 0 0; display: none;">
                    Code does not match. Please try again.
                </p>
            </div>
        </div>
        
        <!-- Footer -->
        <div style="padding: 0.75rem 1.25rem; border-top: 1px solid #e5e7eb; display: flex; align-items: center; justify-content: flex-end; gap: 0.5rem;">
            <button type="button" onclick="closeDeleteModal('{{ $id }}')" 
                    class="inline-flex items-center px-3 text-xs font-medium rounded transition" 
                    style="min-height: 32px; font-family: Poppins, sans-serif; background-color: #f3f4f6; color: #374151;">
                {{ $cancelText }}
            </button>
            <button type="button" id="{{ $id }}-confirm-btn"
                    class="inline-flex items-center px-3 text-xs font-medium rounded transition" 
                    style="min-height: 32px; font-family: Poppins, sans-serif; background-color: #dc2626; color: white; opacity: 0.5; cursor: not-allowed;"
                    disabled>
                <span class="material-symbols-outlined mr-1" style="font-size: 14px;">delete</span>
                {{ $confirmText }}
            </button>
        </div>
    </div>
</div>

<form id="{{ $id }}-form" method="POST" style="display: none;">
    @csrf
    @method('DELETE')
</form>

@once
@push('scripts')
<script>
let deleteModalData = {};

function generateCode() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let code = '';
    for (let i = 0; i < 6; i++) {
        code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return code;
}

function showDeleteModal(modalId, deleteUrl) {
    const modal = document.getElementById(modalId);
    const codeDisplay = document.getElementById(modalId + '-verification-code');
    const codeInput = document.getElementById(modalId + '-code-input');
    const confirmBtn = document.getElementById(modalId + '-confirm-btn');
    const errorMsg = document.getElementById(modalId + '-error-msg');
    
    // Generate new code
    const code = generateCode();
    deleteModalData[modalId] = { code: code, url: deleteUrl };
    
    // Display code
    codeDisplay.textContent = code;
    
    // Reset input
    codeInput.value = '';
    confirmBtn.disabled = true;
    confirmBtn.style.opacity = '0.5';
    confirmBtn.style.cursor = 'not-allowed';
    errorMsg.style.display = 'none';
    
    // Show modal
    modal.style.display = 'flex';
}

function closeDeleteModal(modalId) {
    const modal = document.getElementById(modalId);
    modal.style.display = 'none';
    delete deleteModalData[modalId];
}

function validateDeleteCode(modalId) {
    const codeInput = document.getElementById(modalId + '-code-input');
    const confirmBtn = document.getElementById(modalId + '-confirm-btn');
    const errorMsg = document.getElementById(modalId + '-error-msg');
    
    const enteredCode = codeInput.value.toUpperCase();
    const correctCode = deleteModalData[modalId]?.code;
    
    if (enteredCode === correctCode) {
        confirmBtn.disabled = false;
        confirmBtn.style.opacity = '1';
        confirmBtn.style.cursor = 'pointer';
        errorMsg.style.display = 'none';
        
        confirmBtn.onclick = function() {
            const form = document.getElementById(modalId + '-form');
            form.action = deleteModalData[modalId].url;
            form.submit();
        };
    } else {
        confirmBtn.disabled = true;
        confirmBtn.style.opacity = '0.5';
        confirmBtn.style.cursor = 'not-allowed';
        if (enteredCode.length === 6) {
            errorMsg.style.display = 'block';
        } else {
            errorMsg.style.display = 'none';
        }
    }
}

// Global function for easy access
window.showDeleteModal = function(deleteUrl, modalId = 'delete-modal') {
    const modal = document.getElementById(modalId);
    const codeDisplay = document.getElementById(modalId + '-verification-code');
    const codeInput = document.getElementById(modalId + '-code-input');
    const confirmBtn = document.getElementById(modalId + '-confirm-btn');
    const errorMsg = document.getElementById(modalId + '-error-msg');
    
    // Generate new code
    const code = generateCode();
    deleteModalData[modalId] = { code: code, url: deleteUrl };
    
    // Display code
    codeDisplay.textContent = code;
    
    // Reset input
    codeInput.value = '';
    confirmBtn.disabled = true;
    confirmBtn.style.opacity = '0.5';
    confirmBtn.style.cursor = 'not-allowed';
    errorMsg.style.display = 'none';
    
    // Show modal
    modal.style.display = 'flex';
};
</script>
@endpush
@endonce
